backport

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,12 +1,9 @@
-
 name: build
 
 on:
   push:
-    branches: [ master, "REL-*" ]
+    branches: [ main, "REL-*"]
   workflow_dispatch:
-
-
 
 jobs:
   build:
@@ -15,17 +12,22 @@ jobs:
     env:
        MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
     steps:
+    - name: Cancel previous Action
+      uses: styfle/cancel-workflow-action@0.6.0
+      with:
+        access_token: ${{ github.token }}
     - uses: actions/checkout@v2
-    - name: Set up JDK 1.8
-      uses: actions/setup-java@v1
+    - uses: actions/setup-java@v2
       with:
-        java-version: 1.8
-    - name: Clean settings.xml
-      run: rm -rf ~/.m2/settings.xml
-    - name: Create settings.xml
-      uses: s4u/maven-settings-action@v1
+        distribution: 'adopt'
+        java-version: 8
+    - uses: s4u/maven-settings-action@v2
       with:
-        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.SONATYPE_PASSWORD}}"}]'      
+        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.SONATYPE_PASSWORD}}"}]'
+    - uses: crazy-max/ghaction-import-gpg@v3
+      with:
+        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
+        passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
     - uses: actions/cache@v1
       with:
         path: ~/.m2/repository
@@ -33,14 +35,21 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-maven-
     - name: Build with Maven
-      run: mvn -B -Pdeploy,ossrh deploy --file pom.xml  -Dgpg.skip=true
+      run: mvn -B -Pdeploy,ossrh -U deploy
+      #continue-on-error: true
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Junit Tests            # Name of the check run which will be created
+        path: '**/target/surefire-reports/TEST-*.xml'    # Path to test results
+        reporter: java-junit       # Format of test results
+        only-summary: 'true'
+
     - name: Publish to codecov
       run: bash <(curl -s https://codecov.io/bash)
-      if: github.ref == 'refs/heads/master'
-      continue-on-error: true
-    - name: Publish Test Report
-      uses: scacap/action-surefire-report@v1
-      if: always()
-      with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+      if: github.ref == 'refs/heads/main'
+
+
 
