Let's see if this is nicer.

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -33,9 +33,13 @@ jobs:
     - name: Build with Maven
       run: mvn -B -Pdeploy,ossrh -U deploy
       #continue-on-error: true
-    - name: Publish Test Report
-      uses: scacap/action-surefire-report@v1
-      if: ${{ success() || failure()}}
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Junit Tests            # Name of the check run which will be created
+        path: '**/target/surefire-reports/TEST-*.xml'    # Path to test results
+        reporter: java-junit       # Format of test results
     - name: Publish to codecov
       run: bash <(curl -s https://codecov.io/bash)
       if: github.ref == 'refs/heads/main'
